export {default as Hero} from './Hero/Hero'
export {default as Player} from './Player/Player'
export {default as NewRelease} from './NewRelease/NewRelease'
export {default as PopularRelease} from './PopularRelease/PopularRelease'
export {default as ViewChart} from './ViewChart/ViewChart'